"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Send, Loader2, CheckCircle2, AlertTriangle } from "lucide-react"
import Image from "next/image"

export function ContactForm() {
    const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle")
    const [formData, setFormData] = useState({
        name: "",
        email: "",
        subject: "Technical Inquiry",
        message: ""
    })
    const [errorMsg, setErrorMsg] = useState("")

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        setStatus("loading")
        setErrorMsg("")

        try {
            const res = await fetch("/api/contact", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(formData)
            })

            if (res.ok) {
                setStatus("success")
                setFormData({ name: "", email: "", subject: "Technical Inquiry", message: "" })
            } else {
                const data = await res.json()
                setErrorMsg(data.error || "Uplink failed. Transmission lost.")
                setStatus("error")
            }
        } catch (err) {
            setErrorMsg("Network latency detected. Failed to transmit.")
            setStatus("error")
        }
    }

    return (
        <div className="w-full lg:w-3/5 flex flex-col gap-12">
            <div className="border-2 border-foreground p-8 lg:p-12 relative overflow-hidden bg-background">
                {status === "success" ? (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="h-[500px] flex flex-col items-center justify-center text-center gap-6"
                    >
                        <div className="w-20 h-20 bg-[#ea580c]/10 rounded-full flex items-center justify-center">
                            <CheckCircle2 className="w-10 h-10 text-[#ea580c]" />
                        </div>
                        <div className="flex flex-col gap-2">
                            <h3 className="text-3xl font-mono font-bold uppercase tracking-tighter">Transmission Confirmed</h3>
                            <p className="text-xs font-mono text-muted-foreground max-w-xs mx-auto">
                                Your inquiry has been stored and indexed. A response will be generated by our systems team shortly.
                            </p>
                        </div>
                        <button
                            onClick={() => setStatus("idle")}
                            className="mt-4 border-2 border-foreground px-8 py-3 text-xs font-mono font-bold uppercase tracking-widest hover:bg-foreground hover:text-background transition-all"
                        >
                            New Transmission
                        </button>
                    </motion.div>
                ) : (
                    <form onSubmit={handleSubmit} className="flex flex-col gap-8">
                        <div className="flex flex-col gap-1">
                            <span className="text-[10px] font-mono text-[#ea580c] uppercase font-bold tracking-widest">// NEW_MESSAGE_LOG</span>
                            <h2 className="text-3xl font-mono font-bold uppercase tracking-tighter">Initialize Contact</h2>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                            <div className="flex flex-col gap-2">
                                <label className="text-[10px] font-mono uppercase font-bold">Identity</label>
                                <input
                                    required
                                    type="text"
                                    placeholder="NAME_OR_ORG"
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    className="bg-foreground/5 border-2 border-foreground p-4 text-xs font-mono outline-none focus:border-[#ea580c]"
                                />
                            </div>
                            <div className="flex flex-col gap-2">
                                <label className="text-[10px] font-mono uppercase font-bold">Return_Address</label>
                                <input
                                    required
                                    type="email"
                                    placeholder="EMAIL_ENDPOINT"
                                    value={formData.email}
                                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                                    className="bg-foreground/5 border-2 border-foreground p-4 text-xs font-mono outline-none focus:border-[#ea580c]"
                                />
                            </div>
                        </div>

                        <div className="flex flex-col gap-2">
                            <label className="text-[10px] font-mono uppercase font-bold">Inquiry_Scope</label>
                            <select
                                value={formData.subject}
                                onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                                className="bg-foreground/5 border-2 border-foreground p-4 text-xs font-mono outline-none focus:border-[#ea580c] appearance-none cursor-pointer"
                            >
                                <option>Technical Inquiry</option>
                                <option>Corporate Partnership</option>
                                <option>SLA Support</option>
                                <option>Security/Bug Bounty</option>
                                <option>Billing Question</option>
                            </select>
                        </div>

                        <div className="flex flex-col gap-2">
                            <label className="text-[10px] font-mono uppercase font-bold">Message_Payload</label>
                            <textarea
                                required
                                rows={8}
                                placeholder="Describe your requisition or query in detail..."
                                value={formData.message}
                                onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                                className="bg-foreground/5 border-2 border-foreground p-4 text-xs font-mono outline-none focus:border-[#ea580c] resize-none"
                            />
                        </div>

                        {status === "error" && (
                            <div className="p-4 border-2 border-red-500 bg-red-500/5 text-red-500 flex items-center gap-3">
                                <AlertTriangle size={18} />
                                <span className="text-[10px] font-mono uppercase">ERROR: {errorMsg}</span>
                            </div>
                        )}

                        <button
                            type="submit"
                            disabled={status === "loading"}
                            className="w-full bg-foreground text-background font-mono py-5 text-sm font-bold uppercase tracking-[0.3em] hover:bg-[#ea580c] transition-all flex items-center justify-center gap-3 disabled:opacity-50"
                        >
                            {status === "loading" ? (
                                <>Processing... <Loader2 size={18} className="animate-spin" /></>
                            ) : (
                                <>Transmit Message <Send size={18} /></>
                            )}
                        </button>
                    </form>
                )}

                <div className="absolute top-0 left-0 w-full h-1 bg-[#ea580c]/20 animate-scanline pointer-events-none" />
            </div>

            {/* Team Image Section */}
            {/* <div className="flex flex-col gap-6">
                <div className="flex items-center gap-4">
                    <span className="text-[10px] tracking-[0.2em] font-mono text-muted-foreground uppercase">// THE_TEAM</span>
                    <div className="flex-1 border-t border-foreground/10" />
                </div>
                <div className="relative aspect-video border-2 border-foreground bg-foreground overflow-hidden group">
                    <Image
                        src="/images/contact-team.png"
                        alt="Nubis engineering team collaborating"
                        fill
                        className="object-cover transition-transform duration-700 group-hover:scale-105"
                    />
                    <div className="absolute bottom-4 right-4 z-10">
                        <span className="text-[8px] font-mono bg-background/80 backdrop-blur-sm px-2 py-1 uppercase tracking-tighter">DATA_CENTER_OPS: TEAM_BETA</span>
                    </div>
                </div>
                <p className="text-[10px] font-mono text-muted-foreground leading-relaxed">
                    Nubis engineers operate 24/7 across multiple timezones to ensure the foundry never stops.
                    Real people, real infrastructure, real-time responses.
                </p>
            </div> */}
        </div>
    )
}
